[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "fontcompare"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
]
dependencies = [
    "fontTools >= 4.0",
]

[tool.maturin]
bindings = "pyo3"
